# Form implementation generated from reading ui file 'BookInfo.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 458)
        self.lb_bookcover = QtWidgets.QLabel(parent=Dialog)
        self.lb_bookcover.setGeometry(QtCore.QRect(10, 10, 310, 434))
        self.lb_bookcover.setText("")
        self.lb_bookcover.setPixmap(QtGui.QPixmap("bookcover.jpg"))
        self.lb_bookcover.setScaledContents(True)
        self.lb_bookcover.setOpenExternalLinks(True)
        self.lb_bookcover.setObjectName("lb_bookcover")
        self.tb_bookinfo = QtWidgets.QTextBrowser(parent=Dialog)
        self.tb_bookinfo.setEnabled(True)
        self.tb_bookinfo.setGeometry(QtCore.QRect(330, 110, 141, 311))
        self.tb_bookinfo.setOpenExternalLinks(True)
        self.tb_bookinfo.setOpenLinks(True)
        self.tb_bookinfo.setObjectName("tb_bookinfo")
        self.pb_next = QtWidgets.QPushButton(parent=Dialog)
        self.pb_next.setGeometry(QtCore.QRect(410, 430, 61, 23))
        self.pb_next.setObjectName("pb_next")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "图书信息"))
        self.pb_next.setText(_translate("Dialog", "Next >>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
