# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\BookList.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tv_booklist = QtWidgets.QTableView(parent=self.centralWidget)
        self.tv_booklist.setGeometry(QtCore.QRect(30, 110, 741, 471))
        self.tv_booklist.setObjectName("tv_booklist")
        self.widget = QtWidgets.QWidget(parent=self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 491, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_booklist = QtWidgets.QLineEdit(parent=self.widget)
        self.le_booklist.setObjectName("le_booklist")
        self.horizontalLayout.addWidget(self.le_booklist)
        self.pb_load = QtWidgets.QPushButton(parent=self.widget)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout.addWidget(self.pb_load)
        self.pb_save = QtWidgets.QPushButton(parent=self.widget)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout.addWidget(self.pb_save)
        self.widget1 = QtWidgets.QWidget(parent=self.centralWidget)
        self.widget1.setGeometry(QtCore.QRect(30, 60, 411, 25))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_isbn_pic = QtWidgets.QLineEdit(parent=self.widget1)
        self.le_isbn_pic.setObjectName("le_isbn_pic")
        self.horizontalLayout_2.addWidget(self.le_isbn_pic)
        self.pb_scan = QtWidgets.QPushButton(parent=self.widget1)
        self.pb_scan.setObjectName("pb_scan")
        self.horizontalLayout_2.addWidget(self.pb_scan)
        mainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "图书管理"))
        self.label.setText(_translate("mainWindow", "目   录"))
        self.pb_load.setText(_translate("mainWindow", "加载"))
        self.pb_save.setText(_translate("mainWindow", "保存"))
        self.label_2.setText(_translate("mainWindow", "条形码"))
        self.pb_scan.setText(_translate("mainWindow", "识别"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
