# Form implementation generated from reading ui file 'BooSearch.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setSizeGripEnabled(True)
        self.pb_search_douban = QtWidgets.QPushButton(parent=Dialog)
        self.pb_search_douban.setGeometry(QtCore.QRect(310, 10, 80, 24))
        self.pb_search_douban.setObjectName("pb_search_douban")
        self.tv_booksearch = QtWidgets.QTableView(parent=Dialog)
        self.tv_booksearch.setGeometry(QtCore.QRect(10, 40, 381, 251))
        self.tv_booksearch.setObjectName("tv_booksearch")
        self.le_search_douban = QtWidgets.QLineEdit(parent=Dialog)
        self.le_search_douban.setGeometry(QtCore.QRect(10, 10, 291, 22))
        self.le_search_douban.setObjectName("le_search_douban")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_search_douban.setText(_translate("Dialog", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
