# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\BookList.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tv_booklist = QtWidgets.QTableView(parent=self.centralWidget)
        self.tv_booklist.setGeometry(QtCore.QRect(30, 150, 741, 431))
        self.tv_booklist.setDragEnabled(True)
        self.tv_booklist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tv_booklist.setObjectName("tv_booklist")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 491, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.le_booklist = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_booklist.setObjectName("le_booklist")
        self.horizontalLayout.addWidget(self.le_booklist)
        self.pb_load = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_load.setObjectName("pb_load")
        self.horizontalLayout.addWidget(self.pb_load)
        self.pb_save = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout.addWidget(self.pb_save)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 60, 411, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.le_isbn_pic = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.le_isbn_pic.setObjectName("le_isbn_pic")
        self.horizontalLayout_2.addWidget(self.le_isbn_pic)
        self.pb_scan = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pb_scan.setObjectName("pb_scan")
        self.horizontalLayout_2.addWidget(self.pb_scan)
        self.le_booklist_2 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_2.setGeometry(QtCore.QRect(30, 100, 91, 21))
        self.le_booklist_2.setObjectName("le_booklist_2")
        self.le_booklist_3 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_3.setGeometry(QtCore.QRect(150, 100, 91, 21))
        self.le_booklist_3.setObjectName("le_booklist_3")
        self.le_booklist_4 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_4.setGeometry(QtCore.QRect(260, 100, 91, 21))
        self.le_booklist_4.setObjectName("le_booklist_4")
        self.le_booklist_5 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_5.setGeometry(QtCore.QRect(370, 100, 91, 21))
        self.le_booklist_5.setObjectName("le_booklist_5")
        self.le_booklist_6 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_6.setGeometry(QtCore.QRect(680, 100, 91, 21))
        self.le_booklist_6.setObjectName("le_booklist_6")
        self.le_booklist_7 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_7.setGeometry(QtCore.QRect(580, 100, 91, 21))
        self.le_booklist_7.setObjectName("le_booklist_7")
        self.le_booklist_8 = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_booklist_8.setGeometry(QtCore.QRect(480, 100, 91, 21))
        self.le_booklist_8.setObjectName("le_booklist_8")
        self.pb_insert = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_insert.setGeometry(QtCore.QRect(680, 60, 75, 23))
        self.pb_insert.setObjectName("pb_insert")
        self.pb_getbookinfo = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_getbookinfo.setGeometry(QtCore.QRect(450, 60, 75, 23))
        self.pb_getbookinfo.setObjectName("pb_getbookinfo")
        mainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "图书管理"))
        self.label.setText(_translate("mainWindow", "目   录"))
        self.pb_load.setText(_translate("mainWindow", "加载"))
        self.pb_save.setText(_translate("mainWindow", "保存"))
        self.label_2.setText(_translate("mainWindow", "条形码"))
        self.pb_scan.setText(_translate("mainWindow", "识别"))
        self.pb_insert.setText(_translate("mainWindow", "插入"))
        self.pb_getbookinfo.setText(_translate("mainWindow", "获取"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
