# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\BookInfo.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 448)
        self.lb_bookcover = QtWidgets.QLabel(parent=Dialog)
        self.lb_bookcover.setGeometry(QtCore.QRect(10, 10, 311, 431))
        self.lb_bookcover.setText("")
        self.lb_bookcover.setPixmap(QtGui.QPixmap("bookcover.jpg"))
        self.lb_bookcover.setScaledContents(True)
        self.lb_bookcover.setObjectName("lb_bookcover")
        self.tb_bookinfo = QtWidgets.QTextBrowser(parent=Dialog)
        self.tb_bookinfo.setEnabled(False)
        self.tb_bookinfo.setGeometry(QtCore.QRect(330, 200, 141, 231))
        self.tb_bookinfo.setObjectName("tb_bookinfo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "图书信息"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
