# Form implementation generated from reading ui file 'generate_license.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ge_Lic(object):
    def setupUi(self, Ge_Lic):
        Ge_Lic.setObjectName("Ge_Lic")
        Ge_Lic.resize(370, 373)
        Ge_Lic.setSizeGripEnabled(True)
        self.te_info = QtWidgets.QTextEdit(parent=Ge_Lic)
        self.te_info.setGeometry(QtCore.QRect(20, 220, 331, 131))
        self.te_info.setObjectName("te_info")
        self.label_6 = QtWidgets.QLabel(parent=Ge_Lic)
        self.label_6.setGeometry(QtCore.QRect(20, 190, 56, 16))
        self.label_6.setObjectName("label_6")
        self.pb_ver = QtWidgets.QPushButton(parent=Ge_Lic)
        self.pb_ver.setGeometry(QtCore.QRect(120, 190, 61, 24))
        self.pb_ver.setObjectName("pb_ver")
        self.pb_create = QtWidgets.QPushButton(parent=Ge_Lic)
        self.pb_create.setGeometry(QtCore.QRect(200, 190, 61, 24))
        self.pb_create.setObjectName("pb_create")
        self.layoutWidget = QtWidgets.QWidget(parent=Ge_Lic)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 30, 235, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_mac = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_mac.setObjectName("le_mac")
        self.verticalLayout_2.addWidget(self.le_mac)
        self.dt_date = QtWidgets.QDateTimeEdit(parent=self.layoutWidget)
        self.dt_date.setObjectName("dt_date")
        self.verticalLayout_2.addWidget(self.dt_date)
        self.le_duration_days = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_duration_days.setObjectName("le_duration_days")
        self.verticalLayout_2.addWidget(self.le_duration_days)
        self.le_memo = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_memo.setObjectName("le_memo")
        self.verticalLayout_2.addWidget(self.le_memo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_path = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.le_path.setObjectName("le_path")
        self.horizontalLayout.addWidget(self.le_path)
        self.pb_path = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pb_path.setObjectName("pb_path")
        self.horizontalLayout.addWidget(self.pb_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Ge_Lic)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 31, 101, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.pb_create_key = QtWidgets.QPushButton(parent=Ge_Lic)
        self.pb_create_key.setGeometry(QtCore.QRect(280, 190, 61, 24))
        self.pb_create_key.setObjectName("pb_create_key")

        self.retranslateUi(Ge_Lic)
        QtCore.QMetaObject.connectSlotsByName(Ge_Lic)

    def retranslateUi(self, Ge_Lic):
        _translate = QtCore.QCoreApplication.translate
        Ge_Lic.setWindowTitle(_translate("Ge_Lic", "授权文件生成器"))
        self.label_6.setText(_translate("Ge_Lic", "授权信息"))
        self.pb_ver.setText(_translate("Ge_Lic", "校  验"))
        self.pb_create.setText(_translate("Ge_Lic", "创  建"))
        self.pb_path.setText(_translate("Ge_Lic", ". . ."))
        self.label.setText(_translate("Ge_Lic", "用户机MAC地址:"))
        self.label_2.setText(_translate("Ge_Lic", "授权开始日期:"))
        self.label_3.setText(_translate("Ge_Lic", "授权时长(天):"))
        self.label_4.setText(_translate("Ge_Lic", " 备注信息:"))
        self.label_5.setText(_translate("Ge_Lic", "保存地址:"))
        self.pb_create_key.setText(_translate("Ge_Lic", "密  钥"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ge_Lic = QtWidgets.QDialog()
    ui = Ui_Ge_Lic()
    ui.setupUi(Ge_Lic)
    Ge_Lic.show()
    sys.exit(app.exec())
