# Form implementation generated from reading ui file 'obavip.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(394, 446)
        Dialog.setSizeGripEnabled(True)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 11, 371, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_domain = QtWidgets.QLineEdit(parent=self.widget)
        self.le_domain.setObjectName("le_domain")
        self.horizontalLayout.addWidget(self.le_domain)
        self.pb_getit = QtWidgets.QPushButton(parent=self.widget)
        self.pb_getit.setObjectName("pb_getit")
        self.horizontalLayout.addWidget(self.pb_getit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pt_iplist = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.pt_iplist.setObjectName("pt_iplist")
        self.verticalLayout.addWidget(self.pt_iplist)
        self.pt_ip = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.pt_ip.setObjectName("pt_ip")
        self.verticalLayout.addWidget(self.pt_ip)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_getit.setText(_translate("Dialog", "Get it!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
