# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\QRmaker.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 488)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.lab_image.setGeometry(QtCore.QRect(270, 20, 431, 421))
        self.lab_image.setText("")
        self.lab_image.setPixmap(QtGui.QPixmap("D:\\work\\GIT\\Python-Study\\tools\\../banana.jpg"))
        self.lab_image.setScaledContents(True)
        self.lab_image.setObjectName("lab_image")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 131, 141))
        self.groupBox.setObjectName("groupBox")
        self.pb_load = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_load.setGeometry(QtCore.QRect(70, 20, 51, 24))
        self.pb_load.setObjectName("pb_load")
        self.pb_read = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_read.setGeometry(QtCore.QRect(70, 50, 51, 24))
        self.pb_read.setObjectName("pb_read")
        self.pb_addback = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_addback.setGeometry(QtCore.QRect(70, 80, 51, 24))
        self.pb_addback.setObjectName("pb_addback")
        self.pb_create = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_create.setGeometry(QtCore.QRect(11, 21, 51, 24))
        self.pb_create.setObjectName("pb_create")
        self.pb_save = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_save.setGeometry(QtCore.QRect(11, 111, 51, 24))
        self.pb_save.setObjectName("pb_save")
        self.pb_logo = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_logo.setGeometry(QtCore.QRect(11, 81, 51, 24))
        self.pb_logo.setObjectName("pb_logo")
        self.pb_background = QtWidgets.QPushButton(parent=self.groupBox)
        self.pb_background.setGeometry(QtCore.QRect(11, 51, 51, 24))
        self.pb_background.setObjectName("pb_background")
        self.te_out = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.te_out.setGeometry(QtCore.QRect(10, 300, 231, 141))
        self.te_out.setObjectName("te_out")
        self.te_info = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.te_info.setGeometry(QtCore.QRect(10, 160, 231, 131))
        self.te_info.setObjectName("te_info")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 10, 91, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pb_anim = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pb_anim.setGeometry(QtCore.QRect(10, 20, 51, 24))
        self.pb_anim.setObjectName("pb_anim")
        self.pb_create_anim = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pb_create_anim.setGeometry(QtCore.QRect(10, 50, 51, 24))
        self.pb_create_anim.setObjectName("pb_create_anim")
        self.pb_save_anim = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pb_save_anim.setGeometry(QtCore.QRect(10, 80, 51, 24))
        self.pb_save_anim.setObjectName("pb_save_anim")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "二维码生成器"))
        self.groupBox.setTitle(_translate("MainWindow", "常规"))
        self.pb_load.setText(_translate("MainWindow", "加  载"))
        self.pb_read.setText(_translate("MainWindow", "读  取"))
        self.pb_addback.setText(_translate("MainWindow", "叠  加"))
        self.pb_create.setText(_translate("MainWindow", "生  成"))
        self.pb_save.setText(_translate("MainWindow", "保  存"))
        self.pb_logo.setText(_translate("MainWindow", "Logo"))
        self.pb_background.setText(_translate("MainWindow", "底  纹"))
        self.groupBox_2.setTitle(_translate("MainWindow", "动态"))
        self.pb_anim.setText(_translate("MainWindow", "动  图"))
        self.pb_create_anim.setText(_translate("MainWindow", "生  成"))
        self.pb_save_anim.setText(_translate("MainWindow", "保  存"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
