# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\QRmaker.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 488)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_image = QtWidgets.QLabel(self.centralwidget)
        self.lab_image.setGeometry(QtCore.QRect(270, 20, 431, 421))
        self.lab_image.setText("")
        self.lab_image.setPixmap(QtGui.QPixmap("D:\\work\\GIT\\Python-Study\\tools\\../banana.jpg"))
        self.lab_image.setScaledContents(True)
        self.lab_image.setObjectName("lab_image")
        self.te_info = QtWidgets.QTextEdit(self.centralwidget)
        self.te_info.setGeometry(QtCore.QRect(10, 160, 251, 131))
        self.te_info.setObjectName("te_info")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 141))
        self.groupBox.setObjectName("groupBox")
        self.pb_load = QtWidgets.QPushButton(self.groupBox)
        self.pb_load.setGeometry(QtCore.QRect(110, 20, 75, 24))
        self.pb_load.setObjectName("pb_load")
        self.pb_read = QtWidgets.QPushButton(self.groupBox)
        self.pb_read.setGeometry(QtCore.QRect(110, 50, 75, 24))
        self.pb_read.setObjectName("pb_read")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 77, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_create = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_create.setObjectName("pb_create")
        self.verticalLayout.addWidget(self.pb_create)
        self.pb_background = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_background.setObjectName("pb_background")
        self.verticalLayout.addWidget(self.pb_background)
        self.pb_logo = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_logo.setObjectName("pb_logo")
        self.verticalLayout.addWidget(self.pb_logo)
        self.pb_save = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_save.setObjectName("pb_save")
        self.verticalLayout.addWidget(self.pb_save)
        self.te_out = QtWidgets.QTextEdit(self.centralwidget)
        self.te_out.setGeometry(QtCore.QRect(10, 310, 251, 131))
        self.te_out.setObjectName("te_out")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "二维码生成器"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.pb_load.setText(_translate("MainWindow", "加载"))
        self.pb_read.setText(_translate("MainWindow", "读取"))
        self.pb_create.setText(_translate("MainWindow", "生成"))
        self.pb_background.setText(_translate("MainWindow", "底纹"))
        self.pb_logo.setText(_translate("MainWindow", "Logo"))
        self.pb_save.setText(_translate("MainWindow", "保存"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
