# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\tools\Rpassword.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 50, 41, 24))
        self.pushButton.setObjectName("pushButton")
        self.getPassword = QtWidgets.QPlainTextEdit(Form)
        self.getPassword.setGeometry(QtCore.QRect(30, 150, 291, 141))
        self.getPassword.setObjectName("getPassword")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 291, 131))
        self.groupBox.setObjectName("groupBox")
        self.passwLen = QtWidgets.QLineEdit(self.groupBox)
        self.passwLen.setGeometry(QtCore.QRect(190, 60, 31, 21))
        self.passwLen.setObjectName("passwLen")
        self.Lcharcbx = QtWidgets.QCheckBox(self.groupBox)
        self.Lcharcbx.setGeometry(QtCore.QRect(10, 30, 80, 20))
        self.Lcharcbx.setCheckable(True)
        self.Lcharcbx.setChecked(True)
        self.Lcharcbx.setObjectName("Lcharcbx")
        self.Ucharcbx = QtWidgets.QCheckBox(self.groupBox)
        self.Ucharcbx.setGeometry(QtCore.QRect(100, 30, 80, 20))
        self.Ucharcbx.setObjectName("Ucharcbx")
        self.Speccbx = QtWidgets.QCheckBox(self.groupBox)
        self.Speccbx.setGeometry(QtCore.QRect(10, 60, 80, 20))
        self.Speccbx.setObjectName("Speccbx")
        self.Numbercbx = QtWidgets.QCheckBox(self.groupBox)
        self.Numbercbx.setGeometry(QtCore.QRect(190, 30, 80, 20))
        self.Numbercbx.setObjectName("Numbercbx")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(130, 60, 51, 16))
        self.label.setObjectName("label")
        self.prefix = QtWidgets.QLineEdit(self.groupBox)
        self.prefix.setGeometry(QtCore.QRect(90, 100, 91, 21))
        self.prefix.setObjectName("prefix")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_2.setObjectName("label_2")
        self.btn_reset = QtWidgets.QPushButton(Form)
        self.btn_reset.setGeometry(QtCore.QRect(340, 260, 41, 24))
        self.btn_reset.setObjectName("btn_reset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "密码生成器"))
        self.pushButton.setText(_translate("Form", "生成"))
        self.groupBox.setTitle(_translate("Form", "参数"))
        self.passwLen.setText(_translate("Form", "8"))
        self.Lcharcbx.setText(_translate("Form", "小写字母"))
        self.Ucharcbx.setText(_translate("Form", "大写字母"))
        self.Speccbx.setText(_translate("Form", "特殊字符"))
        self.Numbercbx.setText(_translate("Form", "数字"))
        self.label.setText(_translate("Form", "密码长度"))
        self.prefix.setText(_translate("Form", "xxzx-"))
        self.label_2.setText(_translate("Form", "前置字符串"))
        self.btn_reset.setText(_translate("Form", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
