# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\TXT2EPUB\Dir.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 404)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\work\\GIT\\Python-Study\\TXT2EPUB\\book2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.tb_dir = QtWidgets.QTextBrowser(parent=Dialog)
        self.tb_dir.setGeometry(QtCore.QRect(10, 10, 261, 381))
        self.tb_dir.setObjectName("tb_dir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "章节目录"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
