# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\TXT2EPUB\Txt2epub.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(572, 270)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.le_txt = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_txt.setGeometry(QtCore.QRect(90, 40, 241, 21))
        self.le_txt.setObjectName("le_txt")
        self.le_author = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_author.setGeometry(QtCore.QRect(290, 80, 111, 21))
        self.le_author.setObjectName("le_author")
        self.le_title = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_title.setGeometry(QtCore.QRect(90, 80, 151, 21))
        self.le_title.setObjectName("le_title")
        self.le_epub = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_epub.setGeometry(QtCore.QRect(90, 130, 311, 21))
        self.le_epub.setObjectName("le_epub")
        self.le_reg = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_reg.setGeometry(QtCore.QRect(90, 170, 241, 21))
        self.le_reg.setObjectName("le_reg")
        self.pb_convert = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_convert.setGeometry(QtCore.QRect(90, 200, 75, 23))
        self.pb_convert.setObjectName("pb_convert")
        self.lb_image = QtWidgets.QLabel(parent=self.centralWidget)
        self.lb_image.setGeometry(QtCore.QRect(410, 30, 141, 201))
        self.lb_image.setText("")
        self.lb_image.setPixmap(QtGui.QPixmap("D:\\work\\GIT\\Python-Study\\TXT2EPUB\\cover.jpeg"))
        self.lb_image.setScaledContents(True)
        self.lb_image.setObjectName("lb_image")
        self.label_5 = QtWidgets.QLabel(parent=self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(250, 80, 53, 15))
        self.label_5.setObjectName("label_5")
        self.pb_epub = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_epub.setGeometry(QtCore.QRect(340, 170, 20, 23))
        self.pb_epub.setObjectName("pb_epub")
        self.pb_txt = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_txt.setGeometry(QtCore.QRect(340, 40, 20, 23))
        self.pb_txt.setObjectName("pb_txt")
        self.pb_reset = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_reset.setGeometry(QtCore.QRect(310, 200, 75, 23))
        self.pb_reset.setObjectName("pb_reset")
        self.widget = QtWidgets.QWidget(parent=self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(21, 30, 30, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_epub.setText(_translate("MainWindow", "^\\s*([第卷][0123456789一二三四五六七八九十零〇百千两]*[章回部节集卷].*)\\s*"))
        self.pb_convert.setText(_translate("MainWindow", "转   换"))
        self.label_5.setText(_translate("MainWindow", "作 者"))
        self.pb_epub.setText(_translate("MainWindow", "."))
        self.pb_txt.setText(_translate("MainWindow", "."))
        self.pb_reset.setText(_translate("MainWindow", "重  置"))
        self.label.setText(_translate("MainWindow", "输 入"))
        self.label_3.setText(_translate("MainWindow", "书 名"))
        self.label_2.setText(_translate("MainWindow", "章 节"))
        self.label_4.setText(_translate("MainWindow", "输 出"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
