# Form implementation generated from reading ui file 'D:\work\GIT\Python-Study\TXT2EPUB\Txt2epub.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 360)
        self.centralWidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.le_txt = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_txt.setGeometry(QtCore.QRect(90, 70, 201, 21))
        self.le_txt.setObjectName("le_txt")
        self.le_author = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_author.setGeometry(QtCore.QRect(380, 120, 151, 21))
        self.le_author.setObjectName("le_author")
        self.le_title = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_title.setGeometry(QtCore.QRect(90, 110, 201, 21))
        self.le_title.setObjectName("le_title")
        self.le_epub = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_epub.setGeometry(QtCore.QRect(90, 160, 451, 21))
        self.le_epub.setObjectName("le_epub")
        self.le_reg = QtWidgets.QLineEdit(parent=self.centralWidget)
        self.le_reg.setGeometry(QtCore.QRect(90, 220, 451, 21))
        self.le_reg.setObjectName("le_reg")
        self.pb_convert = QtWidgets.QPushButton(parent=self.centralWidget)
        self.pb_convert.setGeometry(QtCore.QRect(130, 290, 75, 23))
        self.pb_convert.setObjectName("pb_convert")
        self.lb_image = QtWidgets.QLabel(parent=self.centralWidget)
        self.lb_image.setGeometry(QtCore.QRect(620, 20, 141, 201))
        self.lb_image.setObjectName("lb_image")
        self.label = QtWidgets.QLabel(parent=self.centralWidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 53, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 53, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 53, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 53, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(320, 120, 53, 15))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_convert.setText(_translate("MainWindow", "转   换"))
        self.lb_image.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "输 入"))
        self.label_2.setText(_translate("MainWindow", "章 节"))
        self.label_3.setText(_translate("MainWindow", "书 名"))
        self.label_4.setText(_translate("MainWindow", "输 出"))
        self.label_5.setText(_translate("MainWindow", "作 者"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
